platform:
- x64
environment:
  nodejs_version: "6"
  matrix:
  - node_installer: yarn
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
branches:
  only:
  - master

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g npm@4
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- ps: |
    $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
    $env:PATH = $env:PATH + $wixToolsetBinPath
    [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
    if ((Get-Command "light.exe" -ErrorAction SilentlyContinue) -eq $null)
    {
      Write-Host "Unable to find light.exe in your PATH"
    }

test_script:
- node --version
- npm --version
- npm test -- --installer=%node_installer%

build: off
